import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import { backupLogs } from '../../src/db/schema/backup-logs';

describe('backup schema contract', () => {
  it('runtime schema exposes the verification columns used by the monitor app', () => {
    expect(backupLogs.formatVersion.name).toBe('format_version');
    expect(backupLogs.verificationStatus.name).toBe('verification_status');
    expect(backupLogs.verifiedAt.name).toBe('verified_at');
    expect(backupLogs.verifiedFromR2Key.name).toBe('verified_from_r2_key');
  });

  it('SQL migration adds the same verification columns safely for existing environments', () => {
    const sql = readFileSync(
      new URL('../../scripts/migrate-backup-logs.sql', import.meta.url),
      'utf8'
    );

    expect(sql).toContain('ADD COLUMN IF NOT EXISTS format_version TEXT');
    expect(sql).toContain('ADD COLUMN IF NOT EXISTS verification_status TEXT');
    expect(sql).toContain('ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ');
    expect(sql).toContain('ADD COLUMN IF NOT EXISTS verified_from_r2_key TEXT');
  });

  it('verify DB bootstrap script is a trusted schema-only export without data statements', () => {
    const sql = readFileSync(
      new URL('../../scripts/bootstrap-redprint-schema.sql', import.meta.url),
      'utf8'
    );

    expect(sql).toContain('-- Redprint trusted bootstrap schema');
    expect(sql).toContain('-- Generated by: npm run export:bootstrap-schema');
    expect(sql).toContain('CREATE TABLE');
    expect(sql).not.toContain('\\quit 1');
    expect(sql).not.toMatch(/^\s*COPY\s+.+\s+FROM\s+STDIN;/m);
    expect(sql).not.toMatch(/^\s*INSERT\s+INTO\s+/m);
    expect(sql).not.toMatch(/^\s*SELECT pg_catalog\.setval\(/m);
    expect(sql).not.toMatch(/^\\restrict /m);
    expect(sql).not.toMatch(/^\\unrestrict /m);
  });
});
