import { execFile, spawnSync } from 'node:child_process';
import { readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

const outputPath = fileURLToPath(new URL('./bootstrap-redprint-schema.sql', import.meta.url));
const MAIN_MODULE_PATH = process.argv[1];
const FORBIDDEN_DATA_PATTERNS: RegExp[] = [
  /^\s*COPY\s+.+\s+FROM\s+STDIN;/m,
  /^\s*INSERT\s+INTO\s+/m,
  /^\s*SELECT\s+pg_catalog\.setval\(/m,
];
const NOISY_META_PATTERNS: RegExp[] = [
  /^\s*\\restrict .*\n?/gm,
  /^\s*\\unrestrict .*\n?/gm,
];

export interface BootstrapSchemaSourceConfig {
  url: string;
  envName: 'BACKUP_ADMIN_DATABASE_URL' | 'DATABASE_URL';
}

function createTempOutputPath(): string {
  return join(
    tmpdir(),
    `redprint-bootstrap-schema-${Date.now()}-${Math.random().toString(36).slice(2)}.sql`,
  );
}

export function getSourceConfig(): BootstrapSchemaSourceConfig {
  if (process.env.BACKUP_ADMIN_DATABASE_URL) {
    return {
      url: process.env.BACKUP_ADMIN_DATABASE_URL,
      envName: 'BACKUP_ADMIN_DATABASE_URL',
    };
  }

  if (process.env.DATABASE_URL) {
    return {
      url: process.env.DATABASE_URL,
      envName: 'DATABASE_URL',
    };
  }

  throw new Error(
    'Set BACKUP_ADMIN_DATABASE_URL or DATABASE_URL before exporting bootstrap-redprint-schema.sql.',
  );
}

export function buildHeader(sourceEnvName: string): string {
  return [
    '-- Redprint trusted bootstrap schema',
    '--',
    '-- Generated by: npm run export:bootstrap-schema',
    `-- Generated at: ${new Date().toISOString()}`,
    `-- Source env: ${sourceEnvName}`,
    '--',
    '-- This file is the checked-in schema-only snapshot used for verify DB',
    '-- provisioning and empty-DB recovery drills.',
    '-- Regenerate it whenever the trusted deployed schema changes.',
    '',
  ].join('\n');
}

export function buildPgDumpArgs(source: BootstrapSchemaSourceConfig, tempPath: string): string[] {
  return [
    '--schema-only',
    '--no-owner',
    '--no-privileges',
    '--quote-all-identifiers',
    `--file=${tempPath}`,
    `--dbname=${source.url}`,
  ];
}

export function buildDockerPgDumpArgs(source: BootstrapSchemaSourceConfig): string[] {
  return [
    'run',
    '--rm',
    'postgres:17',
    'pg_dump',
    '--schema-only',
    '--no-owner',
    '--no-privileges',
    '--quote-all-identifiers',
    `--dbname=${source.url}`,
  ];
}

export function validateSchemaOnlySql(schemaSql: string): void {
  if (!schemaSql.includes('CREATE TABLE')) {
    throw new Error('pg_dump output did not contain CREATE TABLE statements.');
  }

  for (const pattern of FORBIDDEN_DATA_PATTERNS) {
    if (pattern.test(schemaSql)) {
      throw new Error(
        'pg_dump output contained data statements. Refusing to replace bootstrap-redprint-schema.sql with a non-schema-only export.',
      );
    }
  }
}

export function normalizeSchemaOnlySql(schemaSql: string): string {
  let normalized = schemaSql;

  for (const pattern of NOISY_META_PATTERNS) {
    normalized = normalized.replace(pattern, '');
  }

  return normalized.replace(/\n{3,}/g, '\n\n');
}

export function maskConnectionString(message: string, source: BootstrapSchemaSourceConfig): string {
  return message.replaceAll(source.url, `***${source.envName}***`);
}

function hasCommand(command: string): boolean {
  const result = spawnSync(command, ['--version'], { stdio: 'ignore' });
  return result.status === 0;
}

async function runLocalPgDump(source: BootstrapSchemaSourceConfig, tempOutputPath: string): Promise<string> {
  await execFileAsync('pg_dump', buildPgDumpArgs(source, tempOutputPath));
  return readFileSync(tempOutputPath, 'utf8');
}

async function runDockerPgDump(source: BootstrapSchemaSourceConfig): Promise<string> {
  const { stdout } = await execFileAsync('docker', buildDockerPgDumpArgs(source), {
    maxBuffer: 50 * 1024 * 1024,
  });
  return stdout;
}

export async function exportBootstrapSchema(): Promise<void> {
  const source = getSourceConfig();
  const tempOutputPath = createTempOutputPath();

  try {
    try {
      let schemaSql: string;

      if (hasCommand('pg_dump')) {
        schemaSql = await runLocalPgDump(source, tempOutputPath);
      } else if (hasCommand('docker')) {
        schemaSql = await runDockerPgDump(source);
      } else {
        throw new Error(
          'Neither local pg_dump nor docker is available. Install postgresql-client or run in a Docker-capable environment.',
        );
      }

      validateSchemaOnlySql(schemaSql);
      writeFileSync(outputPath, `${buildHeader(source.envName)}${normalizeSchemaOnlySql(schemaSql)}`);
    } catch (error) {
      const failure = error as NodeJS.ErrnoException & { stderr?: string };
      const rawMessage = failure.stderr?.trim() || failure.message || String(error);
      throw new Error(maskConnectionString(rawMessage, source));
    }
    process.stdout.write(`Wrote trusted bootstrap schema to ${outputPath}\n`);
  } finally {
    rmSync(tempOutputPath, { force: true });
  }
}

if (MAIN_MODULE_PATH === fileURLToPath(import.meta.url)) {
  await exportBootstrapSchema();
}
